### PR TITLE
Add 1.16.100.51

### PR DESCRIPTION
**Pull request by rtm516**
This update is strange as I can't find the version codes for anything but `armeabi-v7a` and for that version there are 2 these being `951610051` and `971610051`. The latter of which has a higher API level requirement (21)

### CODE REVIEW

**Comment by ChristopherHX** [comment]
x86_64: 981610051, no idea which api level

**Comment by ChristopherHX** [comment]
971610051 is aarch64 not arm32
961610051 is x86

**Comment by rtm516** [comment]
Oh yea thanks for that, how do you get these easily?

**Comment by ChristopherHX** [comment]
I use the aurora store app on my android smartphone.
You can spoof the device to get most apk variants

**Pull request merged**
